### PR TITLE
Add examples for binding parameters

### PR DESCRIPTION
**Pull request by ronald-jaepel**
Here I've expanded the example library to include SMA parameter determinations using the Yamamoto method and the inverse method.

This contains changes from the branch #66  and should be merged after #66  is merged.

### CODE REVIEW

**Comment by schmoelder** [comment]
Thanks for this! #66 is now merged; please rebase onto `dev`.

This could be a good idea to reconsider the structure of our examples. A long standing wish is to separate them into individual repositories where we can side-load optimization results using something like CADET-RDM.

**Comment by schmoelder** [comment]
You might also wanna include the example in the docs [here](https://github.com/fau-advanced-separations/CADET-Process/blob/d497d0c6f23c9601e0efc8e6985bde240d129147/docs/source/index.md?plain=1#L25)

**Comment by ronald-jaepel** [comment]
Done.

**Comment by ronald-jaepel** [comment]
The test fails due to a disk-cache error that I can not reproduce locally. On Windows and Linux all tests complete fine.

**Comment by ronald-jaepel** [comment]
Tests completed, todos done. I think this can be merged.

**Comment by schmoelder** [comment]
Nice, just for peace of mind, did you also build the docs locally to check that they work properly?
(might also be a good idea for further CI tests).

**Pull request merged**
