### PR TITLE
Add support for initial values with linear equality constraints 

### PR DESCRIPTION
**Pull request by schmoelder**
For optimization problems with linear equality constraints, initial values currently need to be specified manually. Since [v1.4.0](https://github.com/modsim/hopsy/blob/main/CHANGELOG.md), hopsy also supports linear equality constraints. This PR integrates this new feature into CADET-Process.

## Todo:
- [x] Add individual method to setup hopsy problem
- [x] Add linear equality constraints to hopsy problem
- [x] Remove checks
- [x] Add tests

### CODE REVIEW

**Comment by schmoelder** [comment]
This PR also includes two commits (f33078b18f5413c3492332b17af1de24519fcb75, 685fe94862ee614b8e063af2f270c39fc83803ae) from #52.

**Comment by schmoelder** [comment]
Should have tested this a bit more locally, but just wanted to get it out. This time, I will try not to force push until we get to cleanup phase before merging.

**Review by flo-schu — APPROVED** [review]
Looks good. I remember we implemented this. And apparently hopsy now supports equality constraints. Perfect

**Comment by schmoelder** [comment]
@flo-schu do you know if we need to add more tests for this? I saw that there is already a `test_linear_equality_constrained_transform` so I think we're good. But just wanted to make sure.

**Comment by flo-schu** [comment]
Oh yes, great we have that. I think we are fine then

**Pull request merged**
