### PR TITLE
Enable colloidal binding

### PR DESCRIPTION
**Pull request by angelamoser1**
Changes as discussed in the [forum](https://forum.cadet-web.de/t/when-does-the-colloidal-binding-update-come-out-for-cadet-process/974/6)

### CODE REVIEW

**Comment by schmoelder** [comment]
Thanks Angela for providing this and thanks @jbreue16 for the support!

**Comment by schmoelder** [comment]
Generally, the PR looks good to me. However, I would like to wait until [#85](https://github.com/modsim/CADET/pull/85) is merged in CADET-Core, in case further changes are made to the interface.

**Comment by ronald-jaepel** [comment]
Tested and it works after I fixed on minor variable name. Can be rebased and merged imo.

**Review by ronald-jaepel — APPROVED** [review]

**Comment by schmoelder** [comment]
closed in b1146747a57062caa8ab85c4394bb52aa024f777

**Pull request closed without merging**
